include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/64.mk


summary := general-purpose data compression software with high compression ratio

home     := http://tukaani.org/xz/
name     := xz
version  := 5.0.4
archive  := $(name)-$(version).tar.bz2
download := $(home)/$(archive)
checksum := \
     md5:741cd3a5f64b23b7bac56ec5b2258715 \
    sha1:7dd986aa42e0181cad3af236826f65514d2f7c19 \
  sha256:5cd9b060d3a1ad396b3be52c9b9311046a1c369e6062aea752658c435629ce92 \
    size:1048328

