include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/64.mk

summary := reads the output of diff and displays a histogram of the insertions, deletions, and modifications per-file
license := MIT
license-file := diffstat.license


name     := diffstat
home     := http://invisible-island.net/$(name)/
version  := 1.55
archive  := $(name)-$(version).tgz
download := ftp://invisible-island.net/$(name)/$(archive)
checksum := \
     md5:630d5278f1cd874dc3cc68cff3fddecf \
    sha1:625650a9f1a27edbb98316adb3013e57c8e2e23a \
  sha256:59a46c75a99f2c373a81880051adc43a17b71c55478691e702c61c13c6d61b55 \
    size:235836
