include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk

summary := A Portable Foreign Function Interface Library
license := X11
license-file := LICENSE

name     := libffi
home     := http://sourceware.org/libffi/
version  := 3.0.11
archive  := $(name)-$(version).tar.gz
download := ftp://sourceware.org/pub/$(name)/$(archive)
checksum := \
     md5:f69b9693227d976835b4857b1ba7d0e3 \
    sha1:bff6a6c886f90ad5e30dee0b46676e8e0297d81d \
  sha256:70bfb01356360089aa97d3e71e3edf05d195599fd822e922e50d46a0055a6283 \
    size:794220
