include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/patch.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk
include /usr/share/cibs/rules/autotools.mk

summary := XML parsing C library
license := X11
license-file := COPYING


name     := expat
home     := http://expat.sourceforge.net/
version  := 2.1.0
archive  := $(name)-$(version).tar.gz
download := http://downloads.sourceforge.net/project/$(name)/$(name)/$(version)/$(archive)
checksum := \
     md5:dd7dab7a5fea97d2a6a43f511449b7cd \
    sha1:b08197d146930a5543a7b99e871cba3da614f6f0 \
  sha256:823705472f816df21c8f6aa026dd162b280806838bb55b3432b0fb1fcca7eb86 \
    size:562616
