include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/64.mk

summary := high-performance event loop library modelled after libevent
license := BSD
license-file := LICENSE


name     := libev
home     := http://software.schmorp.de/pkg/libev.html
version  := 4.11
archive  := $(name)-$(version).tar.gz
download := http://dist.schmorp.de/libev/$(archive)
checksum := \
     md5:cda69b858a1849dfe6ce17c930cf10cd \
    sha1:e7752a518742c0f8086a8005aa7efcc4dcf02ed9 \
  sha256:9f55f16ff6e4d60a1b1fa7f4962af69768468f0d7c362aab6387f52020938cdf \
    size:484766
