include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk


summary := manipulate Unicode strings and  C strings according to the Unicode standard.
license := LGPL
license-file := COPYING.LIB

# build-depends +=
# build-conflicts +=

home     := http://www.gnu.org/software/libunistring/
name     := libunistring
version  := 0.9.3
archive  := $(name)-$(version).tar.gz
download := http://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:db8eca3b64163abadf8c40e5cecc261f \
    sha1:e1ea13c24a30bc93932d19eb5ad0704a618506dd \
  sha256:610d3ec724fbdaa654afe3cff20b9f4d504be3fd296fded2e0f7f764041006a3 \
    size:2555215
