include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk

summary := GNU implementation of the traditional Unix macro processor
license := GPL
license-file := COPYING


name     := gperf
home     := http://www.gnu.org/software/$(name)/
version  := 3.0.4
archive  := $(name)-$(version).tar.gz
download := http://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:c1f1db32fb6598d6a93e6e88796a8632 \
    sha1:e32d4aff8f0c730c9a56554377b2c6d82d0951b8 \
  sha256:767112a204407e62dbc3106647cf839ed544f3cf5d0f0523aaa2508623aad63e \
    size:983500
