include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/noarch.mk


summary := Tool for generating GNU Standards-compliant Makefiles
license := GPL
license-file := COPYING

# build-depends +=
# build-conflicts +=

home     := http://www.gnu.org/software/automake/
name     := automake
version  := 1.11.6
archive  := $(name)-$(version).tar.gz
download := http://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:0286dc30295b62985ca51919202ecfcc \
    sha1:29d7832b148e2157e03ad0d3620fbb7f5a13bc21 \
  sha256:53dbf1945401c43f4ce19c1971baecdbf8bc32e0f37fa3f49fe7b6992d0d2030 \
    size:1637926
