include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/patch.mk
include /usr/share/cibs/rules/autoreconf.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk

summary := Generic library support script
license := GPL
license-file := COPYING

home     := http://www.gnu.org/software/libtool/
name     := libtool
version  := 2.4.2
archive  := $(name)-$(version).tar.gz
download := http://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:d2f3b7d4627e69e13514a40e72a24d50 \
    sha1:22b71a8b5ce3ad86e1094e7285981cae10e6ff88 \
  sha256:b38de44862a987293cd3d8dfae1c409d514b6c4e794ebc93648febf9afc38918 \
    size:2632347
