include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk

summary := GNU readline and history libraries
license := GPL v3+
license-file := COPYING

name     := readline
home     := http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
version  := 6.2
archive  := $(name)-$(version).tar.gz
download := ftp://ftp.cwru.edu/pub/bash/$(archive)
checksum := \
     md5:67948acb2ca081f23359d0256e9a271c \
    sha1:a9761cd9c3da485eb354175fcc2fe35856bc43ac \
  sha256:79a696070a058c233c72dd6ac697021cc64abd5ed51e59db867d66d196a89381 \
    size:2277926
