include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/64.mk
include /usr/share/cibs/rules/autotools.mk

summary := Automatic manpage generator
license := GPL v3
license-file := COPYING

home         := http://www.gnu.org/software/help2man/
name         := help2man
version      := 1.41.1
archive      := $(name)-$(version).tar.gz
download     := http://ftpmirror.gnu.org/$(name)/$(archive)
checksum-help2man-1.41.1.tar.gz := \
     md5:4485615cd699a78eb42444324546942a \
    sha1:6fc95fa4505b14a243a5ebef58dd5776035c5fef \
  sha256:3a650ada9453700e34355770d4f74f257fb1dda1a0f24f44b8a3c1d4cb1ee40d \
    size:192138

# Need perl module Locale::gettext
# configure-options += --enable-nls
