include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk

summary := Perl Compatible Regular Expressions
license := BSD
license-file := LICENCE

# build-conflicts +=

home     := http://www.pcre.org/
name     := pcre
version  := 8.31
archive  := $(name)-$(version).tar.bz2
download := http://sourceforge.net/projects/$(name)/files/$(name)/$(version)/$(archive)/download
checksum := \
     md5:1c9a276af932b5599157f96e945391f0 \
    sha1:1132276bb8bea7cb0662210fb812fbef7791621f \
  sha256:5778a02535473c7ee7838ea598c19f451e63cf5eec0bf0307a688301c9078c3c \
    size:1257162
