include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk


summary := GNU utilities for finding files
license := GPLv3
license-file := COPYING

configure-options += --localstatedir=/var/cache/glocate

build-depends += \

prefix := /usr/gnu

name     := findutils
home     := http://www.gnu.org/software/$(name)/
version  := 4.4.2
archive  := $(name)-$(version).tar.gz
download := http://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:351cc4adb07d54877fa15f75fb77d39f \
    sha1:e8dd88fa2cc58abffd0bfc1eddab9020231bb024 \
  sha256:434f32d171cbc0a5e72cfc5372c6fc4cb0e681f8dce566a0de5b6fccd702b62a \
    size:2149838
