include /usr/share/cibs/rules/64.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/ips.mk

summary := GNU dbm database
license := GPL v3+
license-file := COPYING

name     := gdbm
home     := http://directory.fsf.org/project/gdbm/
version  := 1.10
archive  := $(name)-$(version).tar.gz
download := ftp://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:88770493c2559dc80b561293e39d3570 \
    sha1:441201e9145f590ba613f8a1e952455d620e0860 \
  sha256:23f8134c5b94bbfb06d756a6b78f074fba6e6028cf2fe01341d40b26db773441 \
    size:655599
