include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/64.mk

summary := GNU streams editor
license := GPL
license-file := COPYING

prefix := /usr/gnu

build-depends += \


name     := sed
home     := http://www.gnu.org/software/$(name)/
version  := 4.2
archive  := $(name)-$(version).tar.bz2
download := http://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:41b69b632c0265fc1b16079023499590 \
    sha1:ee7af3cd1ebbc6cdf17a7d1abbce00db0c7b5a0d \
  sha256:ee7755e3ab038e7deecebdf44fd43ad65a96890962c3b44206cce672368b45c8 \
    size:882586
