include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/64.mk

summary := the shell
license := GPL
license-file := COPYING


name     := bash
home     := http://www.gnu.org/software/$(name)/
version  := 4.2
archive  := $(name)-$(version).tar.gz
download := http://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:3fb927c7c33022f1c327f14a81c0d4b0 \
    sha1:487840ab7134eb7901fbb2e49b0ee3d22de15cb8 \
  sha256:a27a1179ec9c0830c65c6aa5d7dab60f7ce1a2a608618570f96bfa72e95ab3d8 \
    size:7009201
