include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/patch.mk
include /usr/share/cibs/rules/autoreconf.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk

configure := $(sourcedir)/openpgm/pgm/configure

summary := open source implementation of the Pragmatic General Multicast (PGM) specification in RFC 3208
license := LGPL
license-file := openpgm/pgm/COPYING

# build-conflicts +=

home     := https://code.google.com/p/openpgm/
name     := libpgm
version  := 5.1.118
archive  := $(name)-$(version).tar.bz2
download := https://openpgm.googlecode.com/files/$(archive)
checksum := \
     md5:f561caa7902220eff4d1e2004ba5eedc \
    sha1:76888874a938c26870096105249990c5fdfa9ec2 \
  sha256:7806ab830e3993db77590877fa8133037a86fb6f22e99418a5c7075d93d3aa8b \
    size:857603
