include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk
include /usr/share/cibs/rules/autotools.mk

summary := SQLite 3
license := public domain
license-file := tea/license.terms

build-depends += \
	library/readline

name     := sqlite3
home     := http://www.sqlite.org/
version  := 3.7.15
archive  := sqlite-autoconf-3071500.tar.gz
download := http://www.sqlite.org/$(archive)
checksum := \
     md5:0d2a2d27b56ac73d49db76dcb6b4619c \
    sha1:7b463b76b7a0e322dcdf7bf2221f6e508511e392 \
  sha256:fee53abf5ce8f44ef37cdc734551d82295fc933f522911d371d3421ccd305d48 \
    size:1846740
